name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.8"

    - name: Install Publish
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        make

    - name: Build site
      run: publish generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Output
        #cname: yourdomain.com  # 可选：如果你有自定义域名